spring:
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update

  datasource:
    username: admin
    password: secret
    url: jdbc:h2:file:./data/clinic

  jackson:
    deserialization:
      # to save time as UTC
      ADJUST_DATES_TO_CONTEXT_TIME_ZONE: false
